// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKEL1rk9UYaBtwDFKK9QtMW7KxbmPhlCc',
    appId: '1:745543281476:web:05d0e7e6f9aa2dec0bc511',
    messagingSenderId: '745543281476',
    projectId: 'basiclabproject',
    authDomain: 'basiclabproject.firebaseapp.com',
    storageBucket: 'basiclabproject.appspot.com',
    measurementId: 'G-QTSW2MD1D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh5BRI4LHAEufgyWstZOOyis5EUjqAWI8',
    appId: '1:745543281476:android:92a82ae3dbe597a00bc511',
    messagingSenderId: '745543281476',
    projectId: 'basiclabproject',
    storageBucket: 'basiclabproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEEQt7z4Xop5BVPEeTyFuxP0B9gb7FS9E',
    appId: '1:745543281476:ios:0f1297080e2bda080bc511',
    messagingSenderId: '745543281476',
    projectId: 'basiclabproject',
    storageBucket: 'basiclabproject.appspot.com',
    iosBundleId: 'com.example.teamProjectUi6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEEQt7z4Xop5BVPEeTyFuxP0B9gb7FS9E',
    appId: '1:745543281476:ios:0f1297080e2bda080bc511',
    messagingSenderId: '745543281476',
    projectId: 'basiclabproject',
    storageBucket: 'basiclabproject.appspot.com',
    iosBundleId: 'com.example.teamProjectUi6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKEL1rk9UYaBtwDFKK9QtMW7KxbmPhlCc',
    appId: '1:745543281476:web:7754b2f19a3358060bc511',
    messagingSenderId: '745543281476',
    projectId: 'basiclabproject',
    authDomain: 'basiclabproject.firebaseapp.com',
    storageBucket: 'basiclabproject.appspot.com',
    measurementId: 'G-QCHYC4D6QS',
  );
}
